#!/bin/bash

# Exit immediately if any command exits with a non-zero status
set -e

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo "This script must be run as root or with sudo privileges."
    exit 1
fi

# This variable configures where sources are checked out
SRC="/gnustep-src"

bootstrap()
{
  # Install necessary build dependencies
  apt-get update
  apt-get install -y git sudo
}

checkout()
{
  # Clone the GNUstep-related repositories
  git clone --depth=1 https://github.com/gnustep/tools-scripts.git ${SRC}/tools-scripts
  git clone --depth=1 https://github.com/gnustep/tools-make.git ${SRC}/tools-make
  git clone --depth=1 https://github.com/gnustep/libobjc2.git ${SRC}/libobjc2
  git clone --depth=1 https://github.com/gnustep/libs-base.git ${SRC}/libs-base
  git clone --depth=1 https://github.com/gnustep/libs-gui.git ${SRC}/libs-gui
  git clone --depth=1 https://github.com/gnustep/libs-back.git ${SRC}/libs-back
  git clone --depth=1 https://github.com/gnustep/apps-gworkspace.git ${SRC}/apps-gworkspace
  git clone --depth=1 https://github.com/gnustep/apps-systempreferences.git ${SRC}/apps-systempreferences
  git clone --depth=1 https://github.com/gnustep/gap ${SRC}/gap
}

tools_scripts()
{
  cd "${SRC}/tools-scripts" && ./install-dependencies-linux
}

gnustep_make() 
{
  # Check if GNUstep.sh exists
  if [ -f "/Developer/Makefiles/GNUstep.sh" ]; then
    echo "tools-make already exists. Skipping installation."
    # shellcheck disable=SC1091
    . /Developer/Makefiles/GNUstep.sh
  else
    pwd
    find / -name debstep
    cp FilesystemLayouts/debstep ${SRC}/tools-make/FilesystemLayouts/debstep
    cd "${SRC}/tools-make" && ./configure \
      --with-layout=debstep \
      --with-config-file=/Library/Preferences/GNUstep.conf \
      --with-library-combo=ng-gnu-gnu \
       && gmake && gmake install
    # shellcheck disable=SC1091
    . /Developer/Makefiles/GNUstep.sh
  fi
}

libobjc2() 
{
  local repo_dir="${SRC}/libobjc2"
  local build_dir="${repo_dir}/Build"
  export GNUSTEP_INSTALLATION_DOMAIN=SYSTEM

  # Check if Build directory exists
  if [ ! -d "${build_dir}" ]; then
    mkdir "${build_dir}"
  fi

  # Change to Build directory and configure/build the project
  if [ -f "/System/Include/Block.h" ] ; then
    echo "libobjc already exists. Skipping installation."
  else
    cd ${build_dir} && cmake .. -DGNUSTEP_INSTALL_TYPE=SYSTEM -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
    gmake
    gmake install
  fi
}

gnustep() 
{
  export GNUSTEP_INSTALLATION_DOMAIN=SYSTEM
  if [ -d "/System/Libraries/gnustep-base/" ] ; then
    echo "gnustep-base already exists. Skipping installation."
  else
    cd "${SRC}/libs-base" && ./configure \
      --with-installation-domain=SYSTEM \
      && gmake && gmake install
  fi
  if [ -d "/System/Libraries/gnustep-gui" ] ; then
    echo "libs-gui already exists.  Skipping installation."
  else
    cd "${SRC}/libs-gui" && ./configure \
      && gmake && gmake install
  fi
  if [ -d "/System/Bundles/libgnustep-back-030.bundle" ] ; then
    echo "libs-back already exists. Skipping installation."
  else
    cd "${SRC}/libs-back" && ./configure \
      && gmake && gmake install
  fi
  if [ -d "/System/Applications/GWorkspace.app" ] ; then
    echo "Gworkspace already exists.  Skipping installation."
  else
    cd "${SRC}/apps-gworkspace" && ./configure && gmake && gmake install
  fi
  if [ -d "/System/Applications/SystemPreferences.app" ] ; then
    echo "SystemPreferences already exists.  Skipping installation."
  else
    cd ${SRC}/apps-systempreferences && gmake && gmake install
  fi
}

developer()
{
  export GNUSTEP_INSTALLATION_DOMAIN=NETWORK
  if [ -d "/Developer/Applications/Gorm.app" ] ; then
    echo "Gorm already exists.  Skipping installation."
  else
    cd "${SRC}/apps-gorm" && gmake && gmake install
  fi
    if [ -d "/Developer/Applications/ProjectCenter.app" ] ; then
    echo "ProjectCenter already exists.  Skipping installation."
  else
    cd "${SRC}/apps-projectcenter" && gmake && gmake install
  fi
}

apps()
{
  export GNUSTEP_INSTALLATION_DOMAIN=LOCAL
  cd ${SRC}/gap/system-apps/Terminal && gmake && gmake install
  cd ${SRC}/gs-textedit && gmake && gmake install
}

cleanup()
{
  # Cleanup GNUstep sources
  rm -rf ${SRC}
}

bootstrap
checkout
tools_scripts
gnustep_make
libobjc2
gnustep
developer
apps
cleanup