#!/bin/bash

# Exit immediately if any command exits with a non-zero status
set -e

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo "This script must be run as root or with sudo privileges."
    exit 1
fi

# This variable configures where sources are checked out
SRC="/gnustep-src"

# Determine number of CPUs when building
CPUS=$(nproc)

bootstrap()
{
  # Install necessary build dependencies
  apt-get update
  apt-get install -y git sudo
}

checkout()
{
  # Clone the GNUstep-related repositories
  git clone -b master https://github.com/gnustep/tools-scripts.git ${SRC}/tools-scripts --depth=1
  git clone -b make-2_9_1 https://github.com/gnustep/tools-make.git ${SRC}/tools-make --depth=1
  git clone -b v2.2 https://github.com/gnustep/libobjc2.git ${SRC}/libobjc2 --depth=1
  git clone -b swift-5.10-RELEASE https://github.com/apple/swift-corelibs-libdispatch.git ${SRC}/swift-corelibs-libdispatch --depth=1
  git clone -b swift-5.10-RELEASE https://github.com/apple/swift-corelibs-foundation ${SRC}/swift-corelibs-foundation --depth=1 
  git clone -b base-1_29_0 https://github.com/gnustep/libs-base.git ${SRC}/libs-base --depth=1
  git clone -b gui-0_30_0 https://github.com/gnustep/libs-gui.git ${SRC}/libs-gui --depth=1
  git clone -b back-0_30_0 https://github.com/gnustep/libs-back.git ${SRC}/libs-back --depth=1
  git clone -b master https://github.com/gnustep/apps-gworkspace.git ${SRC}/apps-gworkspace --depth=1
  git clone -b master https://github.com/gnustep/apps-systempreferences.git ${SRC}/apps-systempreferences --depth=1
  git clone -b master https://github.com/gnustep/apps-gorm ${SRC}/apps-gorm --depth=1
  git clone -b master https://github.com/gnustep/apps-projectcenter ${SRC}/apps-projectcenter --depth=1
  git clone -b master https://github.com/gnustep/gap ${SRC}/gap --depth=1
}

source_overlay()
{
  cp FilesystemLayouts/debstep ${SRC}/tools-make/FilesystemLayouts/debstep
}

tools_scripts()
{
  cd "${SRC}/tools-scripts" && ./install-dependencies-linux
}

gnustep_make() 
{
  # Check if GNUstep.sh exists
  if [ -f "/Developer/Makefiles/GNUstep.sh" ]; then
    echo "tools-make already exists. Skipping installation."
    # shellcheck disable=SC1091
    . /Developer/Makefiles/GNUstep.sh
  else
    cd "${SRC}/tools-make" && ./configure \
      --with-layout=debstep \
      --with-config-file=/Library/Preferences/GNUstep.conf \
      --with-library-combo=ng-gnu-gnu \
       && gmake -j"${CPUS}" && gmake install
    # shellcheck disable=SC1091
    . /Developer/Makefiles/GNUstep.sh
  fi
}

libobjc2() 
{
  export GNUSTEP_INSTALLATION_DOMAIN=SYSTEM
  if [ -f "/System/Include/Block.h" ] ; then
    echo "libobjc already exists. Skipping installation."
  else
    mkdir "${SRC}/libobjc2/Build"
    cd "${SRC}/libobjc2/Build" && cmake .. \
      -DGNUSTEP_INSTALL_TYPE=SYSTEM \
      -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_C_COMPILER=clang \
      -DCMAKE_CXX_COMPILER=clang++
    gmake -j"${CPUS}"
    gmake install
  fi
}

libdispatch() 
{
  export GNUSTEP_INSTALLATION_DOMAIN=SYSTEM
  mkdir "${SRC}/swift-corelibs-libdispatch/Build"
  cd "${SRC}/swift-corelibs-libdispatch/Build" && cmake .. \
    -DGNUSTEP_INSTALL_TYPE=SYSTEM \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_C_COMPILER=clang \
    -DCMAKE_CXX_COMPILER=clang++
  gmake -j"${CPUS}"
  gmake install
}

gnustep() 
{
  export GNUSTEP_INSTALLATION_DOMAIN=SYSTEM
  if [ -d "/System/Libraries/gnustep-base/" ] ; then
    echo "gnustep-base already exists. Skipping installation."
  else
    cd "${SRC}/libs-base" && ./configure \
      --with-installation-domain=SYSTEM \
      && gmake -j"${CPUS}" && gmake install
  fi
  if [ -d "/System/Libraries/gnustep-gui" ] ; then
    echo "libs-gui already exists.  Skipping installation."
  else
    cd "${SRC}/libs-gui" && ./configure \
      && gmake -j"${CPUS}" && gmake install
  fi
  if [ -d "/System/Bundles/libgnustep-back-030.bundle" ] ; then
    echo "libs-back already exists. Skipping installation."
  else
    cd "${SRC}/libs-back" && ./configure \
      && gmake -j"${CPUS}" && gmake install
  fi
  if [ -d "/System/Applications/GWorkspace.app" ] ; then
    echo "Gworkspace already exists.  Skipping installation."
  else
    cd "${SRC}/apps-gworkspace" && ./configure && gmake && gmake install
  fi
  if [ -d "/System/Applications/SystemPreferences.app" ] ; then
    echo "SystemPreferences already exists.  Skipping installation."
  else
    cd ${SRC}/apps-systempreferences && gmake -j"${CPUS}" && gmake install
  fi
}

developer()
{
  export GNUSTEP_INSTALLATION_DOMAIN=NETWORK
  if [ -d "/Developer/Applications/Gorm.app" ] ; then
    echo "Gorm already exists.  Skipping installation."
  else
    cd "${SRC}/apps-gorm" && gmake -j"${CPUS}" && gmake install
  fi
    if [ -d "/Developer/Applications/ProjectCenter.app" ] ; then
    echo "ProjectCenter already exists.  Skipping installation."
  else
    cd "${SRC}/apps-projectcenter" && gmake -j"${CPUS}" && gmake install
  fi
}

apps()
{
  export GNUSTEP_INSTALLATION_DOMAIN=LOCAL
  cd ${SRC}/gap/system-apps/Terminal && gmake -j"${CPUS}" && gmake install
}

cleanup()
{
  # Cleanup GNUstep sources
  rm -rf ${SRC}
}

bootstrap
checkout
source_overlay
tools_scripts
gnustep_make
libobjc2
libdispatch
gnustep
developer
apps
cleanup