name: Test Installer on Debian 12 AMD64

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      debian:
        image: debian:bullseye-slim
        options: >-
          --privileged
          --name debian
        ports:
          - 8080:8080

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Test on Debian 12
      run: |
        sudo apt-get update
        sudo apt-get install -y shellcheck
        shellcheck debstep-installer
        sudo ./debstep-installer