name: Test Installer on Debian 12 AMD64

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, debian:bullseye-slim]

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up shell
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Test on Debian 12
      if: matrix.os == 'debian:bullseye-slim'
      run: |
        sudo apt update
        sudo apt install -y shellcheck
        shellcheck debstep-installer
        bash debstep-installer
